foodgram/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('about/', include('django.contrib.flatpages.urls')),
    path('', include('recipes.urls'))
]

urlpatterns += [
        path(
            'about/author/',
            views.flatpage,
            {'url': '/about/author/'},
            name='about_author'
        ),
        path(
            'about/specs/',
            views.flatpage,
            {'url': '/about/specs/'},
            name='about_specs'
        )
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

users/urls.py
from django.urls import path, include

from users.views import SignUp


urlpatterns = [
    path('signup/', SignUp.as_view(), name='sign_up'),
    path('', include("django.contrib.auth.urls"))
]

recipes/models.py
from django.db import models

from users.models import User


class MeasurementsChoices(models.TextChoices):
    kilogramms = 'кг.'
    gramms = 'г.'
    pieces = 'шт.'
    tea_spoon = 'ч.л.'
    table_spoon = 'ст.л.'
    milliliters = 'мл.'
    litters = 'л.'
    taste = 'по вкусу'


class Tag(models.Model):
    name = models.CharField(max_length=20)
    style = models.CharField(max_length=20)
    template_name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    name = models.CharField(
        max_length=100,
        blank=False,
        null=False,
        unique=True
    )
    measurement = models.CharField(
        max_length=15,
        choices=MeasurementsChoices.choices,
        blank=False,
        null=False
    )

    def __str__(self):
        return self.name


class Recipe(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='recipes',
        blank=False,
        null=False
    )
    name = models.CharField(max_length=50, blank=False, null=False)
    tags = models.ManyToManyField(Tag, related_name='recipes', blank=False)
    ingredients = models.ManyToManyField(
        Ingredient,
        related_name='recipes',
        blank=True
    )
    image = models.ImageField(blank=False)
    description = models.TextField(blank=False, null=False)
    cooking_time = models.CharField(max_length=4, blank=False, null=False)
    slug = models.SlugField(unique=True, blank=False, null=False)
    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.name


class RecipeIngredientAmount(models.Model):
    ingredient = models.ForeignKey(
        Ingredient,
        on_delete=models.CASCADE,
        related_name='ingredients',
        blank=False
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='get_amount',
        blank=False
    )
    amount = models.CharField(max_length=3, blank=False, null=False)

    def __str__(self):
        return f'{self.ingredient.name} - {self.recipe.name}'


class Favorite(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='selecting',
        blank=False
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='selected',
        blank=False
    )

    def __str__(self):
        return f'{self.user.username} - {self.recipe.name}'


class ShoppingList(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='choosing',
        blank=False
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='chosen',
        blank=False
    )

    def __str__(self):
        return f'{self.user.username} - {self.recipe.name}'


class Subscription(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        blank=False
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='followed',
        blank=False
    )

    def __str__(self):
        return f'{self.user.username} - {self.user.username}'

users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(unique=True,
                                max_length=20,
                                blank=False,
                                null=False)
    first_name = models.CharField(max_length=80,
                                  blank=False,
                                  null=False)

    def __str__(self):
        return self.username

templates/anonymous_nav.html
<nav class="nav">
    <div class="nav__container container">
        <ul class="nav__items list">
            <li class="nav__item nav__item_active"><a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
        </ul>
        <ul class="nav__items list">
            <li class="nav__item"><a href="{% url 'login' %}" class="nav__link link">Войти</a></li>
            <li class="nav__item"><a href="{% url 'sign_up' %}" class="button button_style_blue">Создать аккаунт</a></li>
        </ul>
    </div>
</nav>

templates/auth_nav.html
{% load сustom_tags %}
<nav class="nav">
    <div class="nav__container container">
        <ul class="nav__items list">
            {% if request.resolver_match.url_name == 'index' %}
            <li class="nav__item nav__item_active"><a href="{% url 'index' %}" class="nav__link link"> Рецепты </a></li>
            {% else %}
            <li class="nav__item"><a href="{% url 'index' %}" class="nav__link link"> Рецепты </a></li>
            {% endif %}
            {% if request.resolver_match.url_name == 'subscriptions' %}
            <li class="nav__item nav__item_active"><a href="{% url 'subscriptions' %}" class="nav__link link"> Мои подписки </a></li>
            {% else %}
            <li class="nav__item"><a href="{% url 'subscriptions' %}" class="nav__link link"> Мои подписки </a></li>
            {% endif %}
            {% if request.resolver_match.url_name == 'create_recipe' %}
            <li class="nav__item nav__item_active"><a href="{% url 'create_recipe' %}" class="nav__link link"> Создать рецепт </a></li>
            {% else %}
            <li class="nav__item"><a href="{% url 'create_recipe' %}" class="nav__link link"> Создать рецепт </a></li>
            {% endif %}
            {% if request.resolver_match.url_name == 'favorites' %}
            <li class="nav__item nav__item_active"><a href="{% url 'favorites' %}" class="nav__link link"> Избранное </a></li>
            {% else %}
            <li class="nav__item"><a href="{% url 'favorites' %}" class="nav__link link"> Избранное </a></li>
            {% endif %}
            {% if request.resolver_match.url_name == 'shopping_list' %}
            <li class="nav__item nav__item_active"><a href="{% url 'shopping_list' %}" class="nav__link link"> Список покупок </a> <span class="badge badge_style_blue nav__badge" id="counter"> {{ request.user|shopping_list_amount }} </span></li>
            {% else %}
            <li class="nav__item"><a href="{% url 'shopping_list' %}" class="nav__link link"> Список покупок </a> <span class="badge badge_style_blue nav__badge" id="counter"> {{ request.user|shopping_list_amount }} </span></li>
            {% endif %}
        </ul>
        <ul class="nav__items list">
            <li class="nav__item"><a href="{% url 'password_change' %}" class="nav__link link"> Изменить пароль </a></li>
              <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link link"> Выход </a></li>
        </ul>
    </div>
</nav>

templates/author.html
{% extends "base.html" %}

{% block title %}
<title> Рецепты автора {{ author.first_name }} </title>
{% endblock %}

{% block style %}
{% load static сustom_tags %}
<link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}

{% block content %}
<header class="header">
    {% if request.user.is_authenticated %}
        {% include 'auth_nav.html' %}
        {% else %}
        {% include 'anonymous_nav.html' %}
    {% endif %}
</header>
    <main class="main container">
        {% csrf_token %}
        <div class="main__header">
            <h1 class="main__title"> {{ author.first_name }} </h1>
            <ul class="tags">
                {% with params=request.GET|obtain_parameters %}
                    {% for tag in tags %}
                        <li class="tags__item">
                            <a id="{{ tag.name }}" class="tags__checkbox tags__checkbox_style_{{ tag.style }}
                            tags__checkbox_{% if tag.name in params %}active{% endif %}"
                            href="/author/{{author.username}}/?{{request|obtain_link:tag}}">
                            </a>
                            <span class="tags__label">{{ tag.template_name }}</span>
                        </li>
                    {% endfor %}
                {% endwith %}
            </ul>

        </div>
        <div class="author-subscribe" data-author="{{ author.id }}">
        {% if request.user.is_authenticated %}
            {% if author|is_subscribed:request %}
            <p style="padding: 0 0 2em 0;"><button class="button button_style_light-blue button_size_auto button_style_light-blue-outline" name="subscribe"><span class="icon-check button__icon"></span> Отписаться от автора</button></p>
            {% else %}
            <p style="padding: 0 0 2em 0;"><button class="button button_style_light-blue button_size_auto" name="subscribe" data-out>Подписаться на автора</button></p>
            {% endif %}
        {% endif %}
        </div>
        <div class="card-list">
        {% for recipe in object_list %}
        <div class="card" data-id="{{ recipe.id }}">
            <a href="{% url 'detail_recipe' recipe.slug %}" class="link" target="_blank"><img src="{{ recipe.image.url }}" alt="Картинка рецепта" class="card__image"></a>
            <div class="card__body">
                <a class="card__title link" href="{% url 'detail_recipe' recipe.slug %}" target="_blank"> {{ recipe.name }} </a>
                <ul class="card__items">
                    {% if recipe.id|if_has_tag:1 %}
                    <li class="card__item"><span class="badge badge_style_orange">Завтрак</span></li>
                    {% endif %}
                    {% if recipe.id|if_has_tag:2 %}
                    <li class="card__item"><span class="badge badge_style_green">Обед</span></li>
                    {% endif %}
                    {% if recipe.id|if_has_tag:3 %}
                    <li class="card__item"><span class="badge badge_style_purple">Ужин</span></li>
                    {% endif %}
                </ul>
                <div class="card__items card__items_column">
                    <p class="card__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин. </p>
                    <p class="card__text"><span class="icon-user"></span> <a href="{% url 'detail_author' recipe.author.username %}" style="color: black"> {{ recipe.author.first_name }} </a></p>
                </div>
            </div>
            <div class="card__footer">
                {% if request.user.is_authenticated %}
                    {% if recipe|is_in_shopping_list:request %}
                    <button class="button button_style_light-blue-outline" name="purchpurchases"><span class="icon-check button__icon"></span> Рецепт добавлен</button>
                    {% else %}
                    <button class="button button_style_light-blue" name="purchpurchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>
                    {% endif %}
                    {% if recipe|is_in_favs:request %}
                    <button class="button button_style_none" name="favorites"><span class="icon-favorite icon-favorite_active"></span></button>
                    {% else %}
                    <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite"></span></button>
                    {% endif %}
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
        {% include 'paginator.html' with object_list=object_list %}
    </main>
<footer class="footer">
    {% include 'footer.html' %}
</footer>
{% endblock %}

{% block js %}
<script src="{% static 'js/components/Purchpurachases.js' %}"></script>
<script src="{% static 'js/components/Favorites.js' %}"></script>
<script src="{% static 'js/components/Subscribe.js' %}"></script>
<script src="{% static 'js/components/MainCards.js' %}"></script>
<script src="{% static 'js/components/CardList.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/components/AuthorRecipe.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'authorRecipe.js' %}"></script>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}
    {% endblock %}

    {% block style %}
    {% endblock %}
</head>
<body class="body">
    {% block content %}
    {% endblock %}

    {% block js %}
    {% endblock %}
</body>
</html>

templates/change_recipe.html
{% extends "base.html" %}

{% block title %}
<title> Редактирование рецепта </title>
{% endblock %}

{% block style %}
{% load static сustom_tags %}
<link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}

{% block content %}
<header class="header">
    {% include 'auth_nav.html' %}
</header>
<main class="main container">
    <div class="main__header">
        <h1 class="main__title">Редактирование рецепта</h1>
    </div>
    <div class="form-container">
        <form class="form" method="POST" action="{% url 'change_recipe' slug %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form__group">
                <label for="id_name" class="form__label">Название рецепта</label>
                <div class="form__field-group">
                    {{ form.name }}
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    <div class="tags">
                        <div class="tags__item">
                            {% for tag_choice, tag_value in form.tags.field.choices %}
                                <div class="tags__item">
                                    <input type="checkbox" name="tags" value="{{tag_choice.instance.pk}}"
                                    id="id_{{tag_choice.instance.value}}" 
                                    class="tags__checkbox tags__checkbox_style_{{tag_choice.instance.style}}"
                                    {% if tag_choice.instance.pk in form.tags.value %} checked {% endif %}>
                                    <label for="id_{{tag_choice.instance.value}}" class="tags__label">
                                        {{tag_choice.instance.template_name}}
                                    </label>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="0">
                        <label for="cantidad" class="form__label" id="cantidadVal"></label>
                    </div>
                    {% for item in form.instance.get_amount.all %}
                    <div class="form__field-item-ingredient">
                        <span> {{ item.ingredient.name }} {{ item.amount }}{{ item.ingredient.measurement }} </span>
                        <span class="form__field-item-delete old-ingredient-delete"></span>
                        <input name="nameIngredient_{{item.ingredient.name}}" type="hidden" value="{{ item.ingredient.name }}">
                        <input name="valueIngredient_{{item.ingredient.name}}" type="hidden" value="{{ item.amount }}">
                        <input name="unitsIngredient_{{item.ingredient.name}}" type="hidden" value="{{ item.ingredient.measurement }}"></div>
                    {% endfor %}
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    <span class="form__input-info"> Для добавления ингредиента введите его название и единицы измерения
                        через запятую. В конце нужно добавить двоеточие. Доступные единицы измерения ('г.', 'кг.', 'мл.', 'л.', 'шт.', 'ч.л.', 'ст.л.' 'по вкусу') <br>
                        Пример: "Апельсин,кг.:" 
                    </span>
                    <span class="form__error">{% if ing_error %} У каждого рецепта должны быть ингредиенты {% endif %}</span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_time" class="form__label">Время приготовления</label>
                <div class="form__field-group form__field-group_time">
                    {{ form.cooking_time }}
                    <label for="id_time" class="form__label">минут</label>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_description" class="form__label">Описание</label>
                <div class="form__field-group">
                    {{ form.description }}
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <span class="form__label">Загрузить фото</span>
                <div class="form__field-group">
                    <label for="id_file" class="form__file-button">Выбрать файл</label>
                    {{ form.image }}
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__footer">
                <button class="button button_style_blue" type="submit"> Сохранить рецепт </button>
            </div>
        </form>
    </div>
</main>
<footer class="footer">
    {% include 'footer.html' %}
</footer>
{% endblock %}

{% block js %}
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/utils/debouncing.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'formRecipe.js' %}"></script>
<script src="{% static 'custom.js' %}"></script>
{% endblock %}

templates/create_recipe.html
{% extends "base.html" %}

{% block title %}
<title> Создание рецепта </title>
{% endblock %}

{% block style %}
{% load static сustom_tags %}
<link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}

{% block content %}
<header class="header">
    {% include 'auth_nav.html' %}
</header>
<main class="main container">
    <div class="main__header">
        <h1 class="main__title">Создание рецепта</h1>
    </div>
    <div class="form-container">
        <form class="form" method="POST" action="{% url 'create_recipe' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form__group">
                <label for="id_name" class="form__label">Название рецепта</label>
                <div class="form__field-group">
                    {{ form.name }}
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    <div class="tags">
                        {% for tag_choice, tag_value in form.tags.field.choices %}
                            <div class="tags__item">
                                <input type="checkbox" name="tags" value="{{tag_choice.instance.pk}}"
                                id="id_{{tag_choice.instance.value}}" 
                                class="tags__checkbox tags__checkbox_style_{{tag_choice.instance.style}}">
                                <label for="id_{{tag_choice.instance.value}}" class="tags__label">
                                    {{tag_choice.instance.template_name}}
                                </label>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="form__group">
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="0">
                        <label for="cantidad" class="form__label" id="cantidadVal"></label>
                    </div>
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    <span class="form__error">{% if ing_error %} У каждого рецепта должны быть ингредиенты {% endif %}</span>
                    <span class="form__input-info"> Для добавления ингредиента введите его название и единицы измерения
                        через запятую. В конце нужно добавить двоеточие. Доступные единицы измерения ('г.', 'кг.', 'мл.', 'л.', 'шт.', 'ч.л.', 'ст.л.' 'по вкусу') <br>
                        Пример: "Апельсин,кг.:" 
                    </span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_time" class="form__label">Время приготовления</label>
                <div class="form__field-group form__field-group_time">
                    {{ form.cooking_time }}
                    <label for="id_time" class="form__label">минут</label>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_description" class="form__label">Описание</label>
                <div class="form__field-group">
                    {{ form.description }}
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <span class="form__label">Загрузить фото</span>
                <div class="form__field-group">
                    <label for="id_file" class="form__file-button">Выбрать файл</label>
                    {{ form.image }}
                    {% if 'image' in form.errors %}
                        <span class="form__error"> Добавьте, пожалуйста, картинку к рецепту </span>
                    {% endif %}
                </div>
            </div>
            <div class="form__footer">
                <button class="button button_style_blue" type="submit">Создать рецепт</button>
            </div>
        </form>
    </div>
</main>
<footer class="footer">
    {% include 'footer.html' %}
</footer>
{% endblock %}

{% block js %}
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/utils/debouncing.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'formRecipe.js' %}"></script>
{% endblock %}

templates/footer.html
<div class="footer__container container">
    <a href="{% url 'index' %}" class="footer__brand link">Продуктовый помощник</a>
    <ul class="footer__items">
        <li class="footer__item"><a href="{% url 'about_author' %}" class="footer__link link">Об авторе </a></li>
        <li class="footer__item"><a href="{% url 'about_specs' %}" class="footer__link link">Технологии</a></li>
    </ul>
</div>

templates/index_anonymous.html
{% extends "base.html" %}

{% block title %}
<title> Рецепты </title>
{% endblock %}

{% block style %}
{% load static сustom_tags %}
<link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}

{% block content %}
<header class="header">
    {% include 'anonymous_nav.html' %}
</header>
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">Рецепты</h1>
            <ul class="tags">
                {% with params=request.GET|obtain_parameters %}
                    {% for tag in tags %}
                        <li class="tags__item">
                            <a id="{{ tag.name }}" class="tags__checkbox tags__checkbox_style_{{ tag.style }}
                            tags__checkbox_{% if tag.name in params %}active{% endif %}"
                            href="/?{{ request|obtain_link:tag}}">
                            </a>
                            <span class="tags__label">{{ tag.template_name }}</span>
                        </li>
                    {% endfor %}
                {% endwith %}
            </ul>
        </div>
        <div class="card-list">
        {% for recipe in object_list %}
        <div class="card" data-id="{{ recipe.id }}">
            <a href="{% url 'detail_recipe' recipe.slug %}" class="link" target="_blank"><img src="{{ recipe.image.url }}" alt="Картинка" class="card__image"></a>
            <div class="card__body">
                <a class="card__title link" href="{% url 'detail_recipe' recipe.slug %}" target="_blank"> {{ recipe.name }} </a>
                <ul class="card__items">
                    {% if recipe.id|if_has_tag:1 %}
                    <li class="card__item"><span class="badge badge_style_orange">Завтрак</span></li>
                    {% endif %}
                    {% if recipe.id|if_has_tag:2 %}
                    <li class="card__item"><span class="badge badge_style_green">Обед</span></li>
                    {% endif %}
                    {% if recipe.id|if_has_tag:3 %}
                    <li class="card__item"><span class="badge badge_style_purple">Ужин</span></li>
                    {% endif %}
                </ul>
                <div class="card__items card__items_column">
                    <p class="card__text"><span class="icon-time"></span> {{ recipe.cooking_time }}</p>
                    <p class="card__text"><span class="icon-user"></span> <a href="{% url 'detail_author' recipe.author.username %}" style="color: black"> {{ recipe.author.first_name }} </a></p>
                </div>
            </div>
            <div class="card__footer">
            </div>
        </div>
        {% endfor %}
        </div>
        {% include 'paginator.html' with object_list=object_list %}
    </main>
<footer class="footer">
    {% include 'footer.html' %}
</footer>
{% endblock %}

{% block js %}
<script src="{% static 'js/components/MainCards.js' %}"></script>
<script src="{% static 'js/components/Purchpurachases.js' %}"></script>
<script src="{% static 'js/components/CardList.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'indexAuth.js' %}"></script>
{% endblock %}

templates/reg.html
{% extends "base.html" %}

{% block title %}
<title> Регистрация </title>
{% endblock %}

{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}

{% block content %}
<header class="header">
    {% include 'anonymous_nav.html' %}
</header>
<main class="main container">
    <div class="main__header">
        <h1 class="main__title">Регистрация</h1>
    </div>
    <div class="form-container">
        <form class="form" method="POST" action="{% url 'sign_up' %}" > 
            {% csrf_token %}
            <div class="form__group">
                <label for="id_first_name" class="form__label">Имя</label>
                <div class="form__field-group">
                    <input type="text" name="first_name" id="id_first_name" class="form__input" value="{{ first_name }}">
                    {% if 'first_name' in form.errors %}
                        {% for error in form.first_name.errors %}
                        <span class="form__error"> {{ error }} </span>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <label for="id_username" class="form__label">Имя пользователя</label>
                <div class="form__field-group">
                    <input type="text" name="username" id="id_username" class="form__input" value="{{ username }}">
                    {% if 'username' in form.errors %}
                        {% for error in form.username.errors %}
                        <span class="form__error"> {{ error }} </span>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <label for="id_email" class="form__label">Адрес электронной почты</label>
                <div class="form__field-group">
                    <input type="email" name="email" id="id_email" class="form__input" value="{{ email }}">
                    {% if 'email' in form.errors %}
                        {% for error in form.email.errors %}
                        <span class="form__error"> {{ error }} </span>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <label for="id_password" class="form__label">Пароль</label>
                <div class="form__field-group">
                    <input type="password" name="password" id="id_password" class="form__input">
                    {% if 'password' in form.errors %}
                        {% for error in form.password.errors %}
                        <span class="form__error"> {{ error }} </span>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="form__footer">
                <button type="submit" class="button button_style_blue">Создать аккаунт</button>
            </div>
        </form>
    </div>
</main>
<footer class="footer">
    {% include 'footer.html' %}
</footer>
{% endblock %}